[repository]
name = "hyprtasking"
authors = ["raybbian"]
commit_pins = [
    ["dd220efe7b1e292415bd0ea7161f63df9c95bfd3", "40e6f615c6e2f7f016d1ee6cfa34668edbeb0cc1"], #v0.53.3
    ["39f3feddbee4a66be9608ed1eb7e73878d596b50", "40e6f615c6e2f7f016d1ee6cfa34668edbeb0cc1"], #v0.53.2
    ["ab1d80f3d6aebd57a0971b53a1993b1c1dfe0b09", "40e6f615c6e2f7f016d1ee6cfa34668edbeb0cc1"], #v0.53.1
    ["ea444c35bb23b6e34505ab6753e069de7801cc25", "40e6f615c6e2f7f016d1ee6cfa34668edbeb0cc1"], #v0.53.0
    ["386376400119dd46a767c9f8c8791fd22c7b6e61", "9611bbd0db23bba9508da44f65989a7dc664d0a9"], #v0.52.2
    ["967c3c7404d4fa00234e29c70df3e263386d2597", "9611bbd0db23bba9508da44f65989a7dc664d0a9"], #v0.52.1
    ["f56ec180d3a03a5aa978391249ff8f40f949fb73", "9611bbd0db23bba9508da44f65989a7dc664d0a9"], #v0.52.0
    ["71a1216abcc7031776630a6d88f105605c4dc1c9", "9388b8ca1bd53a5bfa89b1a6caec7a801df0b6aa"], #v0.51.1
    ["46174f78b374b6cea669c48880877a8bdcf7802f", "9388b8ca1bd53a5bfa89b1a6caec7a801df0b6aa"], #v0.51.0
    ["4e242d086e20b32951fdc0ebcbfb4d41b5be8dcc", "c4e1fa4d0d125c2d3280040343c5e42e4f153a8b"], #v0.50.1
    ["c4a4c341568944bd4fb9cd503558b2de602c0213", "c4e1fa4d0d125c2d3280040343c5e42e4f153a8b"], #v0.50.0
    ["9958d297641b5c84dcff93f9039d80a5ad37ab00", "c4e1fa4d0d125c2d3280040343c5e42e4f153a8b"], #v0.49.0
    ["29e2e59fdbab8ed2cc23a20e3c6043d5decb5cdc", "0d4b6521b4313babf9439d250686b6fd691ab25c"], #v0.48.1
    ["5ee35f914f921e5696030698e74fb5566a804768", "866abe4d617187ddbeba805467c85605f0fcf2d2"], #v0.48.0
    ["882f7ad7d2bbfc7440d0ccaef93b1cdd78e8e3ff", "866abe4d617187ddbeba805467c85605f0fcf2d2"], #v0.47.2
    ["75dff7205f6d2bd437abfb4196f700abee92581a", "32ac67a34bddb088819c93dced4a6862cbc8d4ea"], #v0.47.1
    ["04ac46c54357278fc68f0a95d26347ea0db99496", "aa708a9134cd8f936cd4bcf1b705ab1012b3ea42"], #v0.47.0
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "17940931b59f76ff3b475230648fef261e1e94c8"], #v0.46.2
]

[hyprtasking]
description = "A workspace management plugin."
authors = ["raybbian"]
output = "build/libhyprtasking.so"
build = [
    "meson setup build --buildtype=debug",
    "cd build && meson compile"
]
